mode: auto
system_type: monomer
chain_count: 1
unique_sequence_count: 1
msa_outputs:
- boltz2output/msas/A.a3m
job_name: boltz2
boltz_bin: boltz
diffusion_samples: 1
tmp_root: /var/tmp/boltz_tmp
colabfold_bin: /z/bio/biotools/miniconda/envs/colabfold_beta2/bin/colabfold_search
mmseqs_bin: /z/bio/biotools/mmseqs
db1: /var/tmp/databases/colabfold/uniref30_2103
db_dir: /var/tmp/databases/colabfold/
msa_threads: 64
use_env: 0
